name: 'coseller_migration_poc'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dbt_constraints_enabled: true
  dbt_constraints_pk_enabled: true
  dbt_constraints_fk_enabled: true

models:
  coseller_migration_poc:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
